# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalkulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 343)
        self.tekan = QtWidgets.QPushButton(Dialog)
        self.tekan.setGeometry(QtCore.QRect(160, 230, 111, 28))
        self.tekan.setObjectName("tekan")
        self.input_arus = QtWidgets.QLineEdit(Dialog)
        self.input_arus.setGeometry(QtCore.QRect(160, 80, 113, 22))
        self.input_arus.setObjectName("input_arus")
        self.input_tegangan = QtWidgets.QLineEdit(Dialog)
        self.input_tegangan.setGeometry(QtCore.QRect(160, 160, 113, 22))
        self.input_tegangan.setObjectName("input_tegangan")
        self.label_arus = QtWidgets.QLabel(Dialog)
        self.label_arus.setGeometry(QtCore.QRect(160, 50, 55, 16))
        self.label_arus.setObjectName("label_arus")
        self.label_tegangan = QtWidgets.QLabel(Dialog)
        self.label_tegangan.setGeometry(QtCore.QRect(160, 130, 71, 16))
        self.label_tegangan.setObjectName("label_tegangan")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.tekan.clicked.connect(self.klikhandler)

    def klikhandler(self):
        print(self.input_arus.text())
        print(self.input_tegangan.text())
        print("Saya di klik")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tekan.setText(_translate("Dialog", "Kalkulasi"))
        self.label_arus.setText(_translate("Dialog", "Arus"))
        self.label_tegangan.setText(_translate("Dialog", "Tegangan"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
